version: v1.0.0

baseGoContainer: &baseGoContainer
  name: go
  image: quay.io/deis/lightweight-docker-go:v0.7.0
  sourceMountPath: /go/src/github.com/lovethedrake/brigdrake
  workingDirectory: /go/src/github.com/lovethedrake/brigdrake
  tty: true

baseDindContainer: &baseDindContainer
  name: dind
  image: krancour/dind:18.09.5
  sourceMountPath: /brigdrake
  workingDirectory: /brigdrake
  privileged: true

baseHelmContainer: &baseHelmContainer
  name: helm
  image: dtzar/helm-kubectl:2.14.1
  sourceMountPath: /brigdrake
  workingDirectory: /brigdrake

jobs:

################################################################################
# Utility jobs                                                                 #
################################################################################

  dep:
    containers:
    - <<: *baseGoContainer
      command: dep ensure -v

################################################################################
# Test jobs                                                                    #
################################################################################

  verify-vendored-code:
    containers:
    - <<: *baseGoContainer
      command: dep check

  test-unit:
    containers:
    - <<: *baseGoContainer
      command: go test -timeout 30s -race -coverprofile=coverage.txt -covermode=atomic ./cmd/... ./pkg/...

  upload-coverage-report:
    containers:
    - <<: *baseGoContainer
      command: bash -c "bash <(curl -s https://codecov.io/bash)"

  lint:
    containers:
    - <<: *baseGoContainer
      command: golangci-lint run ./cmd/... ./pkg/...

  lint-chart:
    containers:
    - <<: *baseHelmContainer
      command: helm lint chart/brigdrake

################################################################################
# Build / publish jobs                                                         #
################################################################################

  clean:
    containers:
    - <<: *baseGoContainer
      command: rm -rf bin/

  # This requires a lot of privilege to run and may be useful locally, but
  # favor the DinD variant for use in CI/CD pipelines.
  build-worker-dood:
    containers:
    - name: dood
      image: krancour/dind:18.09.5
      sourceMountPath: /go/src/github.com/lovethedrake/brigdrake
      workingDirectory: /go/src/github.com/lovethedrake/brigdrake
      mountDockerSocket: true
      tty: true
      command: scripts/build-worker-dood.sh

  build-worker-dind:
    containers:
    - <<: *baseDindContainer
      command: scripts/build-worker-dind.sh

  build-and-publish-worker-dind:
    containers:
    - <<: *baseDindContainer
      command: scripts/build-and-publish-worker-dind.sh

  build-chart:
    containers:
    - <<: *baseHelmContainer
      command: scripts/build-chart.sh

  publish-chart:
    containers:
    - name: node
      image: node:10.16.1
      sourceMountPath: /brigdrake
      workingDirectory: /brigdrake
      command: scripts/publish-chart.sh

################################################################################
# Pipelines                                                                    #
################################################################################

pipelines:

################################################################################
# CI pipelines                                                                 #
################################################################################

  test:
    triggers:
    - spec:
        uri: github.com/lovethedrake/drakespec-github
        version: v1.0.0
      config:
        branches:
          ignore:
          - master
          - gh-pages
    jobs:
    - name: lint
    - name: verify-vendored-code
    - name: test-unit
    - name: upload-coverage-report
      dependencies:
      - test-unit
    - name: lint-chart
    - name: build-worker-dind
      dependencies:
      - lint
      - verify-vendored-code
      - test-unit
      - lint-chart
    - name: build-chart
      dependencies:
      - lint
      - verify-vendored-code
      - test-unit
      - lint-chart

  master:
    triggers:
    - spec:
        uri: github.com/lovethedrake/drakespec-github
        version: v1.0.0
      config:
        branches:
          only:
          - master
    jobs:
    - name: lint
    - name: verify-vendored-code
    - name: test-unit
    - name: lint-chart
    - name: build-chart
      dependencies:
      - lint
      - verify-vendored-code
      - test-unit
      - lint-chart
    - name: build-and-publish-worker-dind
      dependencies:
      - build-chart
    - name: publish-chart
      dependencies:
      - build-and-publish-worker-dind

################################################################################
# Release pipeline                                                             #
################################################################################

  release:
    triggers:
    - spec:
        uri: github.com/lovethedrake/drakespec-github
        version: v1.0.0
      config:
        tags:
          only:
          - /v[0-9]+(\.[0-9]+)*(\-.+)?/
    jobs:
    - name: build-chart
    - name: build-and-publish-worker-dind
      dependencies:
      - build-chart
    - name: publish-chart
      dependencies:
      - build-and-publish-worker-dind
