apiVersion: v1
description: Brigade pre-configured with Drake support
name: brigdrake
version: 0.0.1 # This gets automatically overridden by our release process
appVersion: edge # This gets automatically overridden by our release process
home: https://github.com/lovethedrake/brigdrake
sources:
- https://github.com/lovethedrake/brigdrake
maintainers:
- name: Kent Rancourt
  email: kent.rancourt@gmail.com
